### ISSUE TITLE
add IKZ transmission

### ISSUE THREAD

**Issue by aalbino2** [IKZ-Berlin/nomad-ikz-plugin#1]
after adding the transmission in nomad-measurements, also a lab-specific version should be included here

**Comment by ka-sarthak** [comment]
At present, it's not decided what classes from Area B we can use in `transmission`. So moving it to `nomad-measurements`  might take more time. However, I can still move the current version of `transmission` here, as it has been developed in collaboration with Hiroki (from IKZ).
